### PR TITLE
Fix bugs in ByUnmarshallingJSON and GET method polling

### PR DESCRIPTION
**Pull request by garimakhulbe**
Bug fix in ByUnmarshallingJSON and GET method polling

### CODE REVIEW

**Comment by brendandixon** [comment]
@garimakhulbe Looks good, but we should add a test to cover the case in ByUnmarshallingJSON (that is, a test which yields a Body of just blanks).

**Comment by garimakhulbe** [comment]
Okay, let me add that test.

**Comment by garimakhulbe** [comment]
Added test.

**Comment by garimakhulbe** [comment]
Thanks.

**Pull request merged**
