### PR TITLE
Adding ACR suffix to pulic cloud env

### PR DESCRIPTION
**Pull request by mcardosos**
(USgov, China and Germany missing)

Related to [issue 102](https://github.com/Azure/go-autorest/issues/102).

Still incomplete PR.

### CODE REVIEW

**Comment by mcardosos** [comment]
@marstr @jhendrixMSFT @colemickens Should we merge?

**Comment by colemickens** [comment]
It's a bit awkward without it filled in for the other clouds, because the field will be there in the struct, but it won't be blank for the other clouds. I can't remember what's the story on the sovereign clouds though... cc: @SajayAntony

**Comment by salameer** [comment]
Hi @colemickens  and @SajayAntony

**Comment by colemickens** [comment]
(I'll defer to someone else on whether or not this should be merged when the field will be empty for everything but public cloud.)

**Comment by salameer** [comment]
@SajayAntony any thoughts here?

**Comment by djyou** [comment]
Right now, ACR is not yet available in USGov, China, or German. We haven't decided the domain suffix for them either. If not having the filed would be concern, I suppose you can put an empty string or just "azurecr.io" there.

**Comment by salameer** [comment]
Thanks @djyou, we're on it

**Comment by mcardosos** [comment]
Fixed
Feel free to merge @jhendrixMSFT @marstr

**Pull request merged**
