### PR TITLE
Let upstream clients decide if they want to infinitely retry on certain HTTP codes, should not be decided by library

### PR DESCRIPTION
**Pull request by awesomenix**
…in HTTP codes, should not be decided by library

Thank you for your contribution to Go-AutoRest! We will triage and review it as soon as we can.

As part of submitting, please make sure you can make the following assertions:
 - [X ] I've tested my changes, adding unit tests if applicable.
 - [X] I've added Apache 2.0 Headers to the top of any new source files.
 - [X] I'm submitting this PR to the `dev` branch, except in the case of urgent bug fixes warranting their own release.
 - [X] If I'm targeting `master`, I've updated [CHANGELOG.md](https://github.com/Azure/go-autorest/blob/master/CHANGELOG.md) to address the changes I'm making.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
This change was intentional at the request of Terraform so we cannot simply revert it.  Is this causing a problem for you?  We can look at adding some kind of config to opt out of this behavior if necessary.
CC @tombuildsstuff

**Comment by jhendrixMSFT** [comment]
Cancelling the context associated with the request will terminate the retry loop so I don't believe any additional work is required.

**Comment by tombuildsstuff** [comment]
@jhendrixMSFT thanks for the ping :)

@awesomenix out of interest, what's the proposed benefit of not tracking 429's? I can only think this would be to work around the `MaxRetries` option on each SDK Client (which I'd suggest could be removed in favour of fully using Context?). As @jhendrixMSFT has mentioned, when a Context is provided (with a relevant timeout) - AutoRest will continue polling until the context has expired

**Comment by awesomenix** [comment]
@jhendrixMSFT Thanks for looking into this, the issue we are facing is that, we cannot differentiate between long running operations vs operations which are stuck retrying forever due to 429. There are cases we want to bubble up the 429 error code upstream so that external callers can do the retry themselves if required (think of it being used for a sync front end call, though a timeout would definitely work, but having the information that its throttled would be really helpful).

"We can look at adding some kind of config to opt out of this behavior if necessary" - this would be very helpful (way better than the fix i was proposing).

@tombuildsstuff "what's the proposed benefit of not tracking 429's?" we do want to track this information, we dont want the library to infinitely retry instead error out after maxretries and based on the response status code the client can either retry or just bubble up this information upstream.

**Comment by jhendrixMSFT** [comment]
@awesomenix When you say "long running operation" I assume this doesn't refer to an Azure async operation (if it is that's a different discussion).  Do you know if they're including a Retry-After header in that response?  How long is the request taking?  ARM has very strict guidelines on how long a synchronous request should take and if the request is exceeding this then it should be modeled as an async operation.
In the meantime you have a few options for working around the default behavior.
1. Create a context with a timeout or manually cancel the context.  Unfortunately right now if the context is cancelled the response isn't returned (line 237).  We can probably fix this so the response is bubbled up.
2. Write your own sender func that doesn't use `DoRetryForStatusCodes` but some variant of it, then call *Preparer(), CustomSender(), *Responder() individually.

**Comment by awesomenix** [comment]
Thanks for all the help @jhendrixMSFT , will close this PR with no further action.

**Comment by amanohar** [comment]
This issue was closed but adding more information that's relevant as to why an infinite retry on 429 is a bad pattern without an ability to do exponential back offs. Every service is different in terms of how they treat a client when they return 429. 

In some cases it might counts against call limits. And in some cases services might even blacklist a client.

Here is an example of how KeyVault expects clients to retry instead of infinite linear polling:
https://docs.microsoft.com/en-us/azure/key-vault/key-vault-ovw-throttling#how-to-throttle-your-app-in-response-to-service-limits

An important point worth highlighting:

- When this happens, Key Vault returns HTTP status code 429 (Too many requests), and the requests fail. Also, failed requests that return a 429 count towards the throttle limits tracked by Key Vault.

Read world example:
~58 create calls in 10 secs (KV allows 10 creates per 10 second) lead to 3.48K calls because of Go SDK's pattern! :(

Regarding:
>Create a context with a timeout or manually cancel the context. Unfortunately right now if the context is cancelled the response isn't returned (line 237). We can probably fix this so the response is bubbled up.

This is not a good solution because now client loses context of what actually happened.

**Pull request closed without merging**
