### PR TITLE
Corrected DoPollForAsynchronous

### PR DESCRIPTION
**Pull request by brendandixon**
Corrected DoPollForAsynchronous to use the first discovered polling method.

Signed-off-by: Brendan Dixon <brendand@microsoft.com>

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
the person who's merging: please tag accordingly once it's merged.

**Comment by brendandixon** [comment]
@ahmetalpbalkan I've got it.

**Comment by brendandixon** [comment]
@garimakhulbe Ok. You can tag it. :)

**Pull request merged**
