### PR TITLE
Implemented factory pattern for creating senders in autorest/sender.go

### PR DESCRIPTION
**Pull request by tmeckel**
Thank you for your contribution to Go-AutoRest! We will triage and review it as soon as we can.

As part of submitting, please make sure you can make the following assertions:
 - [ ] I've tested my changes, adding unit tests if applicable.
 - [ ] I've added Apache 2.0 Headers to the top of any new source files.
 - [x] I'm submitting this PR to the `dev` branch, except in the case of urgent bug fixes warranting their own release.
 - [ ] If I'm targeting `master`, I've updated [CHANGELOG.md](https://github.com/Azure/go-autorest/blob/master/CHANGELOG.md) to address the changes I'm making.

This PR implements the factory pattern to create senders (Go http clients) based on a factory. Users can override the variable `SenderFactoryInstance` to set an own implementation of the factory type `type SenderFactory func(renengotiation tls.RenegotiationSupport) (*http.Client, error)`. 

The original implementation is preserved as `DefaultSenderFactory` which is set as the default implementation of the sender factory.

### CODE REVIEW

**Comment by tmeckel** [comment]
I'm unable to figure out if my PR caused the test to fail or some other issues. Can someone provide the detailed errors from the Azure DevOps pipelines?

**Comment by tmeckel** [comment]
Okay I identified the issue: the variable `defaultSenders` isn't available in the `dev` branch. Seems to me that the `dev` branch diverged significantly from the `master`. I prepared my PR in the `master` and then read the notes in the _PR template_ which states that, aside urgent bugs, all PR should be placed for the `dev` branch. Seems to me that this isn't the case anymore.

So: **what is the correct target branch to file PR????**

**Comment by jhendrixMSFT** [comment]
Please target the `master` branch.  I'm updating the PR template to remove the outdated instructions, sorry for the confusion.

**Comment by jhendrixMSFT** [comment]
Also, a little info about your scenario and how this addresses it would be helpful.

**Comment by tmeckel** [comment]
@jhendrixMSFT Joel thank for responding so quickly, highly appreciated! ❤

So I'll close this PR, file a new one based on the current `master` branch. 
In this PR I'll elaborate my reasons for adding the sender factory to `go-autorest`.

**Comment by tmeckel** [comment]
@jhendrixMSFT created a new PR at #606

**Pull request closed without merging**
