### PR TITLE
set MaxIdleConnsPerHost to 100 to reuse connections when there is large volume of requests

### PR DESCRIPTION
**Pull request by MartinForReal**
Thank you for your contribution to Go-AutoRest! We will triage and review it as soon as we can.

As part of submitting, please make sure you can make the following assertions:
 - [x] I've tested my changes, adding unit tests if applicable.
 - [x] I've added Apache 2.0 Headers to the top of any new source files.

### CODE REVIEW

**Comment by MartinForReal** [comment]
@jhendrixMSFT  Could you please review the code? Thanks!

**Review by jhendrixMSFT — CHANGES_REQUESTED** [review]
This is a significant increase from the default value of 2.  Is there any reason why you can't use a custom HTTP client, configured as required, and assign it to [Client.Sender](https://github.com/Azure/go-autorest/blob/main/autorest/client.go#L158)?

**Comment by MartinForReal** [comment]
related: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2059

**Comment by MartinForReal** [comment]
I agree. But most of the connections are sent to the same endpoint. And when there are a lot of clients reusing the same transport, the transport will only keep 2 idle connections for this endpoint. It is insufficient when compared with 100 idle connections available.

**Comment by jhendrixMSFT** [comment]
Looks like this was fixed on the kubernetes side so I'm closing this.  Please ping back if you disagree.

**Pull request closed without merging**
