### PR TITLE
Fixes in the method that get cloud information from local file in case of Hybrid cloud model.

### PR DESCRIPTION
**Pull request by radhikagupta5**

### CODE REVIEW

**Comment by marstr** [comment]
What is the rationale behind this change? As far as I can tell it is a breaking-change that could be just as easily navigated around by assigning the `Name` field after you've received the `Environment`.

**Comment by marstr** [comment]
Oh oh, I see what you need. Let me add a commit to your PR that will accomplish what you need without introducing a breaking change.

**Comment by radhikagupta5** [comment]
What is the breaking change here? This change should work for all current code paths.

**Comment by radhikagupta5** [comment]
Fixed go fmt issue and test issue.

**Comment by marstr** [comment]
Adding a parameter to an exported function is a breaking change :) https://github.com/Azure/go-autorest/pull/241/files#diff-3bdeb422d37dc52e27d000a3978232fdR168

**Comment by radhikagupta5** [comment]
No one except us is using this function as it's in the if condition. It should be totally fine.

**Comment by marstr** [comment]
Closing in favor of #242

**Pull request closed without merging**
