### PR TITLE
Update import path case.

### PR DESCRIPTION
**Pull request by shurcooL**
Followup to 91eb6c3e and d13eb8d7.

~~Also update go -> Go in fenced code block highlighting (both work, but this is the correct language name case).~~

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
Omg omg omg first pull request.

**Comment by ahmetalpbalkan** [comment]
I am not sure about Go vs go. I've always used "go" and it served me well. Can you point us to a resource? Does github use pygments?

**Comment by shurcooL** [comment]
> I am not sure about Go vs go. I've always used "go" and it served me well. Can you point us to a resource? Does github use pygments?

If you prefer to stay with `go`, that's not a problem, I will revert that change.

I don't have a source, I myself also started using `go` initially but then over time ended up using `Go` everywhere. It seemed nicer since the language is officially called Go. But I don't want to change it for you if you already use `go` everywhere else.

**Comment by ahmetalpbalkan** [comment]
LGTM thanks.

**Comment by shurcooL** [comment]
No problem! I've updated the commit to remove the go -> Go change and updated the commit message accordingly.

> Omg omg omg first pull request.

I know the feeling. Sorry it's just a tiny one, nothing substantial. But first PRs always tend to be small and grow from there. :)

**Comment by shurcooL** [comment]
By the way, you'll also want to remember to update the repository description. It's currently still the lowercase version:

image

**Comment by brendandixon** [comment]
@shurcooL Thanks.

**Comment by shurcooL** [comment]
Happy to help!

**Pull request merged**
