### PR TITLE
Add FutureAPI interface type

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
To be used for mocking Future response types.

Thank you for your contribution to Go-AutoRest! We will triage and review it as soon as we can.

As part of submitting, please make sure you can make the following assertions:
 - [ ] I've tested my changes, adding unit tests if applicable.
 - [ ] I've added Apache 2.0 Headers to the top of any new source files.
 - [ ] I'm submitting this PR to the `dev` branch, except in the case of urgent bug fixes warranting their own release.
 - [ ] If I'm targeting `master`, I've updated [CHANGELOG.md](https://github.com/Azure/go-autorest/blob/master/CHANGELOG.md) to address the changes I'm making.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Part of the fix for https://github.com/Azure/azure-sdk-for-go/issues/14010

**Review by catalinaperalta — APPROVED** [review]
LGTM, although I dont know if these are all of the functions that the Future would need, but it seems complete.

**Comment by jhendrixMSFT** [comment]
It's all the exported methods currently defined on the `azure.Future` type.

**Comment by catalinaperalta** [comment]
> It's all the exported methods currently defined on the `azure.Future` type.

The `azure.Future` type that's outputted in the generated code right?

**Comment by jhendrixMSFT** [comment]
No, the `Future` type defined in the `autorest/azure` package in this repo.  This is all of the widget-agnostic methods, the others are part of the generated code (similar to track 2).

**Comment by catalinaperalta** [comment]
Ah ok, got it. Thanks for the info! :)

**Pull request merged**
